config/routes.rb
Rails.application.routes.draw do
  root to: 'index#index'
  get 'users/login', :to => 'sessions#index'
  post 'users/login'
  delete 'users/logout', :to =>'sessions#destroy'


  resources :users



  resources :experiments
  resources :sessions, only: [:index, :new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  has_and_belongs_to_many :staff, class_name: "User", join_table: "experiments_staff", association_foreign_key: 'staff_id'
  belongs_to :author, class_name: "User"

  validates_presence_of :title, :staff_size
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, :email, :password, presence: true
  validates :email, uniqueness: true
  belongs_to :role
  has_many :experiments_posted, class_name: "Experiment", foreign_key: :author_id
  has_and_belongs_to_many :experiments_joined, class_name: "Experiment", join_table: "experiments_staff", foreign_key: "staff_id", association_foreign_key: "experiment_id"

  def clearance_levels
    role.name
  end

  def access_token=(given_token)
    if given_token == ENV['FACULTY_ACCESS_TOKEN']
      self.role = Role.find_by(name: "Faculty")
    elsif given_token == ENV['STAFF_ACCESS_TOKEN']
      self.role = Role.find_by(name: "Staff")
    else
      errors.add(:access_token, "Invalid access token")
    end
  end

  def access_token

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_clearance_levels
    session[:role] || :guest
  end
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController

  def index
    @experiments = Experiment.order(created_at: :desc)
  end

  def show
    @user = User.find(session[:user_id])
    @experiment = Experiment.find(params[:id])
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def new
    @experiment = Experiment.new
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def create
    @user = User.find(session[:user_id])
    @experiment = Experiment.new( title: experiment_params[:title],
                                      abstract: experiment_params[:abstract],
                                      introduction: experiment_params[:introduction],
                                      materials: experiment_params[:materials],
                                      results: experiment_params[:results],
                                      discussion: experiment_params[:discussion],
                                      conclusion: experiment_params[:conclusion],
                                      supporting_info: experiment_params[:supporting_info],
                                      acknowledgments: experiment_params[:acknowledgments],
                                      references: experiment_params[:references],
                                      author_contributions: experiment_params[:author_contributions],
                                      author_id: session[:user_id],
                                      staff_size: experiment_params[:staff_size])
    if @experiment.save
      respond_to do |format|
        format.js {}
      end
    else
      @experiment = Experiment.new
      @message = "Missing and/or incorrect information"
      respond_to do |format|
        format.js {render action: 'new'}
      end
    end
  end

  def update
    @lab_staff = User.find(session[:user_id])
    @experiment = Experiment.find(params[:id])
    if @experiment.staff.count < @experiment.staff_size
      @experiment.staff << @lab_staff
    end
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  private
    def experiment_params
       params.require(:experiment).permit(:title, :abstract, :introduction, :materials, :results, :discussion, :conclusion, :supporting_info, :acknowledgments, :author_contributions, :references, :staff_size)
    end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index
    ExampleJob.perform_now "HELLO CHORUS FROGS"
    @experiments = Experiment.order(created_at: :desc)
    @user = User.new
    if request.xhr?
      if session[:user_id]
        @experiments = Experiment.order(created_at: :desc)
        respond_to do |format|
          format.js {render action: 'logged_in_show'}
        end
      else
        respond_to do |format|
          format.js {render action: 'logged_out_show'}
        end
      end
    end
  end

  def logged_in_show
  end

  def logged_out_show
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    respond_to do |format|
      format.js {}
    end
  end

  def new
    @user = User.new
    respond_to do |format|
      format.js {}
    end
  end

  def create
    @user = User.find_by_email(user_params[:email])
    @experiments = Experiment.all
    if @user && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      session[:role] = @user.clearance_levels
      if request.xhr?
        respond_to do |format|
          format.js {}
        end
      else
        redirect_to controller: "experiments", action: "index"
      end
    else
      if request.xhr?
        @user = User.new unless @user
        @message = "Incorrect email or password."
        respond_to do |format|
          format.js { render action: 'new' }
        end
      else
        redirect_to sessions_path
      end
    end
  end

  def destroy
    reset_session
    if request.xhr?
      respond_to do |format|
        format.js {}
      end
    else
      redirect_to controller: "experiments", action: "index"
    end
  end

  private
    def user_params
      params.require(:post).permit(:email, :password, :role)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    if request.xhr?
      respond_to do |format|
        format.js {}
      end
    else
      render 'new'
    end
  end

  def create
    @user = User.new(user_params)
    p @user
    @experiments = Experiment.all
    if @user.save
      session[:user_id] = @user.id
      session[:role] = @user.clearance_levels

      if request.xhr?
        respond_to do |format|
          format.js {}
        end
      else
        redirect_to controller: "experiments", action: "index"
      end
    else
      if request.xhr?
        @user = User.new unless @user
        @message = "Registration information not valid."
        respond_to do |format|
          # @errors = @user.errors
          format.js {render action: 'new'}
        end
      else
        render 'new'
      end
    end

  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :access_token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def signed_in?
    if session[:user_id]
      return true
    else
      false
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/experiments/_index.html.erb
<%= render 'index/navigation'%>
<div class="row">
  <div class="col-xs-1 column"> </div>
  <div class="col-xs-10 column text-center"><h1>Autogenics Experiments List</h1></div>
  <div class="col-xs-1 column"> </div>
</div>
<div class='row'>
  <div class='col-xs-1 column'> </div>
  <div class='col-xs-10 column' id="new-post-exp">
    <% if session[:role] == "Faculty" %>
      <%= button_to "Post New Experiment", new_experiment_path, method: :get, :class => 'btn btn-default', remote: true %>
       <% end %>
<div class='row'>
  <div class='col-xs-1 column'> </div>
  <div id="example-links" class='col-xs-10 column experiments-list'>
  <br>
    <ul>
      <% @experiments.each do |experiment| %>
        <li class='title' id= <%= experiment.id %> >
          <%= link_to "#{experiment.title}", experiment_path(experiment), remote: true %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col-xs-1 column"> </div>
</div>

app/views/experiments/_new.html.erb
<%= render 'index/navigation'%>
<div class="row">
  <div class="col-xs-1"></div>
  <div class="col-xs-10">
    <div class="card">
      <div class="card-block text-center">
        <div class="panel-heading">
          <h1 class="panel-header">Post a New Experiment </h1>
        </div>
          <div class="panel-body" id="create-exp">

            <%= form_for @experiment, remote: true, authenticity_token: true do |f| %>
              <p>
                <%= f.label :title %><br>
                <%= f.text_field :title %>
              </p>
              <p>
                <%= f.label :staff_size %><br>
                <%= f.number_field :staff_size, size: "35x10"  %>
              </p>
              <p>
                <%= f.label :abstract %><br>
                <%= f.text_area :abstract, size: "35x10"  %>
              </p>
              <p>
                <%= f.label :introduction %><br>
                <%= f.text_area :introduction, size: "35x10"  %>
              </p>
                <%= f.label :materials %><br>
                <%= f.text_area :materials, size: "35x10"  %>
              <p>
                <%= f.label :results %><br>
                <%= f.text_area :results, size: "35x10"  %>
              </p>
              <p>
                <%= f.label :discussion %><br>
                <%= f.text_area :discussion, size: "35x10"  %>
              </p>
              <p>
                <%= f.label :conclusion %><br>
                <%= f.text_area :conclusion, size: "35x10"  %>
              </p>
              <p>
                <%= f.label :supporting_info %><br>
                <%= f.text_area :supporting_info, size: "35x10"  %>
              </p>
              <p>
                <%= f.label :acknowledgments %><br>
                <%= f.text_area :acknowledgments, size: "35x10"  %>
              </p>
              <p>
                <%= f.label :author_contributions %><br>
                <%= f.text_area :author_contributions, size: "35x10"  %>
              </p>
              <p>
                <%= f.label :references %><br>
                <%= f.text_area :references, size: "35x10"  %>
              </p>

              <%= f.submit 'Post Experiment', :class => 'btn btn-default'  %>
            <% end %>
            <% if @message %>
              <div class="errors-block">
                <%= @message %>
              </div>
            <% end %>
          </div>
      </div>
    </div>
  </div>
  <div class="col-xs-1"></div>
</div>

app/views/experiments/_show.html.erb
<%= render 'index/navigation'%>
<div class= "row">
  <div class="col-xs-1"></div>
  <div class="col-xs-10">
    <div id="main-content">
      <div class="sub-content" id="article-title">
        <h1><em> <%= experiment.title %></em> </h1>
      </div>
      <div class="sub-content" id="article-abstract">
        <h3> Abstract </h3>
        <p class="local_hidden"> <%= experiment.abstract %> </p>
      </div>
      <div class="sub-content" id="article-intro">
        <h3> Introduction </h3>
        <p class="local_hidden"> <%= experiment.introduction %> </p>
      </div>
      <div class="sub-content" id="article-material">
        <h3> Materials and Methods </h3>
        <p class="local_hidden">
          <%= experiment.materials %>
        </p>
      </div>
      <div class="sub-content" id="article-results">
        <h3> Results </h3>
        <p class="local_hidden"> <%= experiment.results  %> </p>
      </div>
      <div class="sub-content" id="article-disc">
        <h3> Discussion </h3>
        <p class="local_hidden"> <%= experiment.discussion %> </p>
      </div>
      <div class="sub-content" id="article-con">
        <h3> Conclusion </h3>
         <p class="local_hidden"> <%= experiment.conclusion %> </p>
      </div>
      <div class="sub-content" id="article-sup-info">
        <h3> Supporting Info </h3>
         <p class="local_hidden"> <%= experiment.supporting_info %> </p>
      </div>
      <div class="sub-content" id="article-acknow">
        <h3> Acknowledgments </h3>
         <p class="local_hidden"> <%= experiment.acknowledgments %> </p>
      </div>
      <div class="sub-content" id="article-author-cont">
        <h3> Author Contributions </h3>
        <p class="local_hidden"> <%= experiment.author_contributions %> </p>
      </div>
      <div class="sub-content" id="article-ref">
        <h3> References </h3>
        <p class="local_hidden"> <%= experiment.references %> </p>
      </div>
    </div>
    <div class="sub-content" id="staff-content">
        <h3> Current Experiment Staff </h3>
        <ul>
          <li>Lead Researcher: <%= experiment.author.name %></li>
            <% if experiment.staff.empty? %>
              <li id="no-staff">This experiment currently has no staff signed up!</li>
            <% else %>
              <% experiment.staff.each do |staff| %>
                <li>Lab Staff: <%= staff.name %></li>
              <% end %>
            <% end %>
            <li class="list-staff"></li>
        </ul>
        <div class="sign-up-button">
          <% if @user.role.name == "Staff" && @experiment.staff.include?(@user) == false && @experiment.staff.count < @experiment.staff_size %>
            <%= form_for experiment, url: {controller: 'experiments', action: "update"}, remote: true, authenticity_token: true do |f| %>
            <%= f.submit 'Sign Up For Experiment!', :class => 'btn btn-default' %>
            <% end %>
          <br>
          <% end %>
        </div>
    </div>
  </div>

  <div class="col-xs-1">
  </div>


</div>

app/views/experiments/create.js.erb
$('#ajax-content').html("<%= escape_javascript render partial: 'show', locals: { :experiment => @experiment }, :id => @experiment.id %>")

app/views/experiments/index.html.erb
<%= render 'navigation'%>
<div class='row'>
  <div class='col-xs-1 column'> </div>
  <div class='col-xs-10 column text-center'><h1>Autogenics Experiments List</h1></div>
  <div class='col-xs-1 column'> </div>
</div>
<div class='row'>
  <div class='col-xs-1 column'> </div>
  <div class='col-xs-10 column'>
    <% if session[:role] == "Faculty" %>
      <%= button_to "Post New Experiment", new_experiment_path, method: :get , :class => 'btn btn-default'%>
    <% end %>
  </div>
  <div class='col-xs-1 column'> </div>
</div>
<div class='row'>
  <div class='col-xs-1 column'> </div>
  <div class='col-xs-10 column experiments-list'>
  <br>
    <ul>
      <% @experiments.each do |experiment| %>
        <li class='title' id= <%= experiment.id %> >
          <%= link_to "#{experiment.title}", experiment_path(experiment)  %>
        </li><br>
      <% end %>
    </ul>
  </div>

  <div class='col-xs-1 column'> </div>
</div>

app/views/experiments/new.html.erb
<div class="row">
  <div class="col-xs-1"></div>
  <div class="col-xs-10">
    <div class="card">
      <div class="card-block text-center">
        <div class="panel-heading">
          <h1 class="panel-header">Post a New Experiment </h1>
        </div>
          <div class="panel-body">

            <%= form_for @experiment do |f| %>
              <p>
                <%= f.label :title %><br>
                <%= f.text_field :title %>
              </p>
              <p>
                <%= f.label :staff_size %><br>
                <%= f.number_field :staff_size, size: "35x10"  %>
              </p>
              <p>
                <%= f.label :abstract %><br>
                <%= f.text_area :abstract, size: "35x10"  %>
              </p>
              <p>
                <%= f.label :introduction %><br>
                <%= f.text_area :introduction, size: "35x10"  %>
              </p>
                <%= f.label :materials %><br>
                <%= f.text_area :materials, size: "35x10"  %>
              <p>
                <%= f.label :results %><br>
                <%= f.text_area :results, size: "35x10"  %>
              </p>
              <p>
                <%= f.label :discussion %><br>
                <%= f.text_area :discussion, size: "35x10"  %>
              </p>
              <p>
                <%= f.label :conclusion %><br>
                <%= f.text_area :conclusion, size: "35x10"  %>
              </p>
              <p>
                <%= f.label :supporting_info %><br>
                <%= f.text_area :supporting_info, size: "35x10"  %>
              </p>
              <p>
                <%= f.label :acknowledgments %><br>
                <%= f.text_area :acknowledgments, size: "35x10"  %>
              </p>
              <p>
                <%= f.label :author_contributions %><br>
                <%= f.text_area :author_contributions, size: "35x10"  %>
              </p>
              <p>
                <%= f.label :references %><br>
                <%= f.text_area :references, size: "35x10"  %>
              </p>

              <%= f.submit 'Post Experiment', :class => 'btn btn-default'  %>
            <% end %>
          </div>
      </div>
    </div>
  </div>
  <div class="col-xs-1"></div>
</div>

app/views/experiments/new.js.erb
$('#ajax-content').html("<%= escape_javascript render partial: 'new', locals: {message: @message, user: @user} %>")

app/views/experiments/show.html.erb
<div class= "row">
  <div class="col-xs-1"></div>
  <div class="col-xs-10">
    <div id="main-content">
      <div class="sub-content" id="article-title">
        <h1><em> <%= @experiment.title %></em> </h1>
      </div>
      <div class="sub-content" id="article-abstract">
        <h3> Abstract </h3>
        <p class="local_hidden"> <%= @experiment.abstract %> </p>
      </div>
      <div class="sub-content" id="article-intro">
        <h3> Introduction </h3>
        <p class="local_hidden"> <%= @experiment.introduction %> </p>
      </div>
      <div class="sub-content" id="article-material">
        <h3> Materials and Methods </h3>
        <p class="local_hidden">
          <%= @experiment.materials %>
        </p>
      </div>
      <div class="sub-content" id="article-results">
        <h3> Results </h3>
        <p class="local_hidden"> <%= @experiment.results  %> </p>
      </div>
      <div class="sub-content" id="article-disc">
        <h3> Discussion </h3>
        <p class="local_hidden"> <%= @experiment.discussion %> </p>
      </div>
      <div class="sub-content" id="article-con">
        <h3> Conclusion </h3>
         <p class="local_hidden"> <%= @experiment.conclusion %> </p>
      </div>
      <div class="sub-content" id="article-sup-info">
        <h3> Supporting Info </h3>
         <p class="local_hidden"> <%= @experiment.supporting_info %> </p>
      </div>
      <div class="sub-content" id="article-acknow">
        <h3> Acknowledgments </h3>
         <p class="local_hidden"> <%= @experiment.acknowledgments %> </p>
      </div>
      <div class="sub-content" id="article-author-cont">
        <h3> Author Contributions </h3>
        <p class="local_hidden"> <%= @experiment.author_contributions %> </p>
      </div>
      <div class="sub-content" id="article-ref">
        <h3> References </h3>
        <p class="local_hidden"> <%= @experiment.references %> </p>
      </div>
    </div>
    <div class="sub-content" id="staff-content">
        <h3> Current Experiment Staff </h3>
        <ul>
          <li>Lead Researcher: <%= @experiment.author.name %></li>
            <% if @experiment.staff.empty? %>
              <li id="no-staff">This experiment currently has no staff signed up!</li>
            <% else %>
              <% @experiment.staff.each do |staff| %>
                <li>Lab Staff: <%= staff.name %></li>
              <% end %>
            <% end %>
            <li class="list-staff"></li>
        </ul>
        <div class="sign-up-button">
          <% if @user.role.name == "Staff" && @experiment.staff.include?(@user) == false && @experiment.staff.count < @experiment.staff_size %>
            <%= form_for experiment, url: {controller: 'experiments', action: "update"}, remote: true do |f| %>
            <%= f.submit 'Sign Up For Experiment!', :class => 'btn btn-default' %>
            <% end %>
          <br>
          <% end %>
        </div>
    </div>
  </div>

  <div class="col-xs-1">
  </div>


</div>

app/views/experiments/show.js.erb
$("#ajax-content").html("<%= escape_javascript(render(:partial => 'show', locals: { experiment: @experiment })) %>")

app/views/experiments/update.js.erb
$('li#no-staff').hide();
$('div.sign-up-button').hide();
$('li.list-staff').html("Lab Staff: <%= escape_javascript(@lab_staff.name) %>");

app/views/index/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top">
    <div class="navbar-header container-fluid" id="navfluid">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "AUTOGENICS", root_path, :class => 'navbar-brand', remote: true %>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
        <% if session[:user_id] %>
        <li><% @user = User.find(session[:user_id]) %>
          <%= button_to "Log out", users_logout_path, method: :delete, :id => 'login-link', :class => 'nav navbar-nav', "data-toggle" => "collapse", "data-target" => ".navbar-collapse.in", remote: true, authenticity_token: true %></li>
        <% else %>
          <li><%= button_to "Log in", users_login_path, method: :get, :id => 'logout-link', :class => 'nav navbar-nav', "data-toggle" => "collapse", "data-target" => ".navbar-collapse.in", remote: true %></li>
          <li><%= button_to "Registration", new_user_path, method: :get, :id => 'reg-link', :class => 'nav navbar-nav', "data-toggle" => "collapse", "data-target" => ".navbar-collapse.in", remote: true %></li>
          </ul>
        <% end %>
      </div>
    </div>
</nav>

app/views/index/index.html.erb
<div id="ajax-content">
</div>

app/views/index/logged_in_show.js.erb
$('#ajax-content').html("<%= escape_javascript (render 'experiments/index', locals: {experiments: @experiments}) %>");

app/views/index/logged_out_show.js.erb
$('#ajax-content').html("<%= escape_javascript (render 'sessions/index') %>");

app/views/index/navigation_show.js.erb
$('#navigation-contain').html("<%= escape_javascript (render 'navigation')%>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>AutogenicsClientProject</title>
    <%= csrf_meta_tags %>
    <!-- BOOTSTRAP Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!--  BOOTSTRAP Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- LOCAL CSS -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>


    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>

    <!-- BOOTSTRAP Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- LOCAL JS-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>var signedIn = <%== signed_in?.to_json  %></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/staff/_staff_sign_up.html.erb
<div class="row">
  <div class="col-xs-1"></div>
  <div class="col-xs-10">
    <div class=panel-heading>
      <h1 class="panel-header">Sign up</h1>
    </div>
    <p>Please type your name to confirm you will be involved in <%= experiment.title %> for the duration of the experiment.</p>

    <%= form_for experiment_path do |f| %>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
      <%= f.submit 'Sign Up', :class => 'btn btn-default' %>
    <% end %>
    </div>
  </div>
</div>

app/views/staff/_staff_signs_up.html.erb
<div class="row">
  <div class="col-xs-1"></div>
  <div class="col-xs-10">
    <div class=panel-heading>
      <h1 class="panel-header">Sign up</h1>
    </div>
    <p>Please type your name to confirm you will be involved in <%= experiment.title %> for the duration of the experiment.</p>

    <%= form_for experiment_path do |f| %>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
      <%= f.submit 'Sign Up', :class => 'btn btn-default' %>
    <% end %>
    </div>
  </div>
</div>

app/views/users/_new.html.erb
<%= render 'index/navigation'%>
<div class="row">
  <div class="col-xs-1 column"></div>
  <div class="col-xs-10 column">
    <% if @message %>
      <div class="errors-block">
        <%= @message %>
      </div>
    <% end %>
    <div class="card-block text-center">
      <div class="panel-heading">
        <h3 class="panel-header">Create Account</h3>
      </div>
      <div class="panel-body">
        <%= form_for :user, url:{action: "create"}, remote: true, authenticity_token: true do |f| %>
          <div class="form-group">
            <label for="user[full_name]">Full Name</label>
            <%= f.text_field :name, :class => "form-control", :placeholder => "name..." %>
          </div>
          <div class="form-group">
            <label for="user[email]">Email</label>
            <%= f.text_field :email, :class => "form-control", :placeholder => "email..." %>
          </div>
          <div class="form-group">
            <label for="user[password]">Password</label>
            <%= f.password_field :password, :class => "form-control", :placeholder => "password..." %>
          </div>
          <div class="form-group">
            <label for="access_token">Access Token</label>
            <%= f.text_field :access_token, :class => "form-control", :placeholder => "access token..." %>
          </div>
          <%= f.submit "Create", :id => "session-submit", :class => "btn btn-default" %>
        <%end%>
      </div>
    </div>
  </div>
  <div class="col-xs-1 column"></div>
</div>

app/views/users/create.js.erb
$('#ajax-content').html("<%= escape_javascript (render partial: 'experiments/index', locals: {experiments: @experiments, message: @message, user: @user}) %>");

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-1 column"></div>
  <div class="col-xs-10 column">
    <div class="card-block text-center">
      <div class="panel-heading">
        <h3 class="panel-header">Create Account</h3>
      </div>
      <div class="panel-body">
        <%= form_for :user, url:{action: "create"} do |f| %>
          <div class="form-group">
            <label for="user[full_name]">Full Name</label>
            <%= f.text_field :name, :class => "form-control", :placeholder => "name..." %>
          </div>
          <div class="form-group">
            <label for="user[email]">Email</label>
            <%= f.text_field :email, :class => "form-control", :placeholder => "email..." %>
          </div>
          <div class="form-group">
            <label for="user[password]">Password</label>
            <%= f.password_field :password, :class => "form-control", :placeholder => "password..." %>
          </div>
          <div class="form-group">
            <label for="access_token">Access Token</label>
            <%= f.text_field :access_token, :class => "form-control", :placeholder => "access token..." %>
          </div>
          <%= f.submit "Create", :class => "btn btn-default" %>
        <%end%>
      </div>
    </div>
  </div>
  <div class="col-xs-1 column"></div>
</div>

app/views/users/new.js.erb
$('#ajax-content').html("<%= escape_javascript (render 'new') %>");